name: abank_project
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  carousel_slider: ^4.2.1
  cloud_firestore: ^4.13.3
  email_validator: ^2.1.17
  feather_icons: ^1.2.0
  firebase_auth: ^4.15.0
  firebase_core: ^2.24.0
  firebase_storage: ^11.5.3
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.3.5
  intl: ^0.18.1
  qr_code_scanner: ^1.0.1
  qr_flutter: ^4.1.0
flutter_native_splash:
  color: '363636'
  custom_navigation_bar: ^0.8.2

  android_12:
    color: '363636'

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - images/Abank (1).png
    - icons/lock.png
    - icons/credit-limit.png
    - icons/cvv.png
    - images/logo.png
    - images/50548.png
    - images/1.png
    - images/2.png
    - images/3.png
    - images/

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: fonts/Poppins-Bold.ttf
          weight: 700
        - asset: fonts/Poppins-Black.ttf
          weight: 900
