name: abank_project
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  cloud_firestore: ^4.13.3
  cloud_firestore_platform_interface: ^6.0.7
  feather_icons: ^1.2.0
  firebase_analytics: ^10.7.2
  firebase_core: ^2.22.0
  flutter:
    sdk: flutter
  intl: ^0.18.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - images/Abank (1).png
    - icons/lock.png
    - icons/credit-limit.png
    - icons/cvv.png
    - images/logo.png

  fonts:
    - family: Poppins
      fonts: 
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: fonts/Poppins-Bold.ttf
          weight: 700
        - asset: fonts/Poppins-Black.ttf
          weight: 900
